New task
jspuser123/frappe1 pull request #2
Opened 2023-03-27 13:21 UTC by jspuser123

sir pls review

2023-03-28 06:02 UTC, karthikeyan5 requested changes

2023-03-28 06:02 UTC, karthikeyan5 commented on coolapp/coolapp/doctype/article/article.json
> +   "read_only_depends_on": "eval:!(doc.__islocal)",
explain this to me

2023-03-28 06:02 UTC, karthikeyan5 commented on coolapp/coolapp/doctype/library_membership/library_membership.js
> +
remove empty spaces

2023-03-28 06:02 UTC, karthikeyan5 commented on coolapp/coolapp/doctype/library_membership/library_membership.json
> +  "membership_type"
move to top

2023-03-28 06:02 UTC, karthikeyan5 commented on coolapp/coolapp/doctype/library_membership/library_membership.py
> +
remove unwanted empty spaces

2023-03-28 06:02 UTC, karthikeyan5 commented on coolapp/coolapp/doctype/library_membership/library_membership.py
> +			if self.library_member and self.from_date and self.to_date and self.paid:
- move this condition to "madatory depends on" field.
- then simplify this if conditions

2023-03-28 06:02 UTC, karthikeyan5 commented on coolapp/coolapp/doctype/library_membership/library_membership.py
> +			("There is an active membership for this member")
fix this

2023-03-28 06:02 UTC, karthikeyan5 commented on coolapp/coolapp/doctype/library_membership/library_membership.py
> +		elif self.membership_type == 'group':
existing membership validation for group membership

2023-03-28 06:02 UTC, karthikeyan5 commented on coolapp/coolapp/doctype/library_transaction/library_transaction.json
> +   "depends_on": "eval:(doc.type == 'Issued' || doc.type == 'Return')",
also add "mandatory depends on"

2023-03-28 06:02 UTC, karthikeyan5 commented on coolapp/coolapp/doctype/library_transaction/library_transaction.py
> -
not yet reviewed. please remove unwanted empty lines.

2023-03-28 13:48 UTC, jspuser123 commented on coolapp/coolapp/doctype/library_transaction/library_transaction.json
> +   "depends_on": "eval:(doc.type == 'Issued' || doc.type == 'Return')",
OK add "mandatory depends on"

2023-03-28 13:53 UTC, jspuser123 commented on coolapp/coolapp/doctype/library_membership/library_membership.js
> +
ok remove spaces

2023-03-28 13:54 UTC, jspuser123 commented on coolapp/coolapp/doctype/library_membership/library_membership.json
> +  "membership_type"
change move to top

2023-03-28 13:55 UTC, jspuser123 commented on coolapp/coolapp/doctype/library_membership/library_membership.py
> +			if self.library_member and self.from_date and self.to_date and self.paid:
ok add "madatory depends on" field.
then if conditions

2023-03-28 13:56 UTC, jspuser123 commented on coolapp/coolapp/doctype/library_membership/library_membership.py
> +			("There is an active membership for this member")
ok fix

2023-03-28 13:56 UTC, jspuser123 commented on coolapp/coolapp/doctype/library_membership/library_membership.py
> +		elif self.membership_type == 'group':
new validation add

2023-03-28 14:04 UTC, jspuser123 commented on coolapp/coolapp/doctype/article/article.json
> +   "read_only_depends_on": "eval:!(doc.__islocal)",
If eval:!(doc.__islocal) is true, the document is local(not saved)

local = local to your browser, i.e. not on the server

eval: = evaluate

! = not equals

doc = document

__islocal = is not saved

2023-03-29 06:56 UTC, karthikeyan5 requested changes

2023-03-29 06:56 UTC, karthikeyan5 commented on coolapp/coolapp/doctype/library_membership/library_membership.js
> +			frm.doc.is_group=true
please fix this.

2023-03-29 06:56 UTC, karthikeyan5 commented on coolapp/coolapp/doctype/library_membership/library_membership.js
> +				else
simplify this if condition.

2023-03-29 07:30 UTC, jspuser123 commented on coolapp/coolapp/doctype/library_membership/library_membership.js
> +			frm.doc.is_group=true
ok fix this bug

2023-04-13 04:59 UTC, merged